### ISSUE TITLE
今天突然刮削无结果的情况

### ISSUE THREAD

**Issue by smilejoker365** [JavScraper/Emby.Plugins.JavScraper#110]
有没有人和我一样的情况啊

**Comment by BmanMoo** [comment]
same here, in Scheduled Tasks show "Failed" on JavScraper plugin

emby server version : 4.6.0.22

**Comment by 277383761** [comment]
我也是4.6.0.22无法刮削了.....奇怪

**Comment by JavScraper** [comment]
看下日志是不是报错了，记得4.6+的接口有变化。

**Comment by 277383761** [comment]
任务里有一个点击出来是如下这样的提示,看不懂

Method not found: 'System.Threading.Tasks.Task MediaBrowser.Controller.Providers.IProviderManager.SaveImage(MediaBrowser.Controller.Entities.BaseItem, MediaBrowser.Model.Configuration.LibraryOptions, System.IO.Stream, System.ReadOnlyMemory`1<char>, MediaBrowser.Model.Entities.ImageType, System.Nullable`1<int32>, System.Threading.CancellationToken)'.
at Emby.Plugins.JavScraper.JavPersonTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&amp; stateMachine)
at Emby.Plugins.JavScraper.JavPersonTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)</int32></char>

**Comment by 277383761** [comment]
但是日志里我看了,好像没看到相关的txt

**Comment by 277383761** [comment]
日志太长,不知道怎么看

**Comment by smilejoker365** [comment]
@BmanMoo 是的，4.6.0.22无法刮削，我回滚到4.5.4.0正式版了，beta版我不用了

**Comment by 277383761** [comment]
是的,4.6.0.22无法刮削，我回滚到4.5.4.0正式版了,,,但是新的问题又出现了,正式版的播放记录不会刷新怎么回事????
