### ISSUE TITLE
头像刮削失败 求更新

### ISSUE THREAD

**Issue by xingfanxia** [JavScraper/Emby.Plugins.JavScraper#167]
Method not found: 'System.Threading.Tasks.Task MediaBrowser.Controller.Providers.IProviderManager.SaveImage(MediaBrowser.Controller.Entities.BaseItem, MediaBrowser.Model.Configuration.LibraryOptions, System.IO.Stream, System.ReadOnlyMemory`1<char>, MediaBrowser.Model.Entities.ImageType, System.Nullable`1<int32>, System.Threading.CancellationToken)'.
at Emby.Plugins.JavScraper.JavPersonTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&amp; stateMachine)
at Emby.Plugins.JavScraper.JavPersonTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)</int32></char>

**Comment by JoJoWuBeBetter** [comment]
我更新完4.6.0也不行了。回滚回去就好了

**Comment by bzvroo** [comment]
> 我更新完4.6.0也不行了。回滚回去就好了

如何回滚求大大指教

**Comment by JoJoWuBeBetter** [comment]
> > 我更新完4.6.0也不行了。回滚回去就好了
> 
> 如何回滚求大大指教

你看emby安装的目录，有一个是system.old的文件夹 那个就是老的。如果没有的话去emby官方的Github下一个
