### ISSUE TITLE
Failure on downloading actress's avatars

### ISSUE THREAD

**Issue by cascadahk** [JavScraper/Emby.Plugins.JavScraper#171]
Pls have a look on this function

**Comment by cascadahk** [comment]
Method not found: 'System.Threading.Tasks.Task MediaBrowser.Controller.Providers.IProviderManager.SaveImage(MediaBrowser.Controller.Entities.BaseItem, MediaBrowser.Model.Configuration.LibraryOptions, System.IO.Stream, System.ReadOnlyMemory`1<char>, MediaBrowser.Model.Entities.ImageType, System.Nullable`1<int32>, System.Threading.CancellationToken)'.
at Emby.Plugins.JavScraper.JavPersonTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&amp; stateMachine)
at Emby.Plugins.JavScraper.JavPersonTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)</int32></char>
