### ISSUE TITLE
emby 4.6版本 使用Javbus获取封面失败

### ISSUE THREAD

**Issue by MccYcore** [JavScraper/Emby.Plugins.JavScraper#175]
2021-05-29 11:40:33.911 Info Emby.Plugins.JavScraper.Services.ImageService: /pics/thumb/897x.jpg
2021-05-29 11:40:33.951 Error Server: Error processing request
	*** Error Report ***
	Version: 4.6.1.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 3.10.102 (root@build3) (gcc version 4.9.3 20150311 (prerelease) (crosstool-NG 1.20.0) ) #15284 SMP Sat May 19 04:44:02 CST 2018
	Framework: .NET Core 3.1.13
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	MediaBrowser.Common.Extensions.ResourceNotFoundException: MediaBrowser.Common.Extensions.ResourceNotFoundException: Exception of type 'MediaBrowser.Common.Extensions.ResourceNotFoundException' was thrown.
	   at Emby.Plugins.JavScraper.Services.ImageService.DoGet(String url, Nullable`1 type)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: JavScraper
	TargetSite: Void MoveNext()
	
2021-05-29 11:40:33.953 Info Server: http/1.1 Response 404 to 192.168.14.6. Time: 49ms. http://192.168.14.11:32769/emby/Plugins/JavScraper/Image?url=%2fpics%2fthumb%2f897x.jpg

**Comment by JavScraper** [comment]
再试试看新版本

**Comment by maxererer** [comment]
我也是，有女优介绍，但是就是没有封面和背景图

**Comment by geekfibonacci** [comment]
same same，有女优与片名信息，但是没有封面和背景图。
