### ISSUE TITLE
v1.2021.603.740 能获取封面图，无法下载，附错误日志

### ISSUE THREAD

**Issue by MateorChan** [JavScraper/Emby.Plugins.JavScraper#194]
2021-06-17 22:42:40.640 Info App: GetImageResponse-/emby/Plugins/JavScraper/Image?url=http%3a%2f%2fpics.dmm.co.jp%2f%2fdigital%2fvideo%2fcawd00215%2fcawd00215pl.jpg&type=Backdrop
2021-06-17 22:42:40.640 Error App: System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Emby.Plugins.JavScraper.Services.ImageProxyService.GetImageResponse(String url, ImageType type, CancellationToken cancellationToken)

**Comment by MateorChan** [comment]
emby 4.6.2.0

**Comment by MateorChan** [comment]
读了一下源码，发现获取图片的时候会拼接URL，前缀是dashboard里面显示的本地地址，如果是空的话，就会出现这个问题，把本地地址加上就可以了

**Comment by spldmanager** [comment]
我也碰到同样的问题，加上本地地址也没用，不知道是不是bug
