### ISSUE TITLE
更新了emby 4.6.4 搜刮器终于正常可以用了

### ISSUE THREAD

**Issue by bilbil188** [JavScraper/Emby.Plugins.JavScraper#207]
emby 4.6.4 搜刮器终于正常可以用了

**Comment by 4488dsq** [comment]
你JavOrganize 可用吗？
我不可用了
Access to the path '/yuan/#recycle' is denied.
at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
at System.IO.Enumeration.FileSystemEnumerator`1.DequeueNextDirectory()
at System.IO.Enumeration.FileSystemEnumerator`1.DirectoryFinished()
at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength)
at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
at Emby.Plugins.JavScraper.JavOrganizeTask.GetFilesToOrganize(String path)
at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
at Emby.Plugins.JavScraper.JavOrganizeTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)

**Comment by bilbil188** [comment]
把EMBY升级到最新版本就能用了 记得挂代理



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月3日(星期六) 中午1:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JavScraper/Emby.Plugins.JavScraper] 更新了emby 4.6.4 搜刮器终于正常可以用了 (#207)





 
你JavOrganize 可用吗？
 我不可用了
 Access to the path '/yuan/#recycle' is denied.
 at System.IO.Enumeration.FileSystemEnumerator1.CreateDirectoryHandle(String path, Boolean ignoreNotFound) at System.IO.Enumeration.FileSystemEnumerator1.DequeueNextDirectory()
 at System.IO.Enumeration.FileSystemEnumerator1.DirectoryFinished() at System.IO.Enumeration.FileSystemEnumerator1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength)
 at System.IO.Enumeration.FileSystemEnumerator1.MoveNext() at System.Linq.Enumerable.SelectEnumerableIterator2.ToList()
 at Emby.Plugins.JavScraper.JavOrganizeTask.GetFilesToOrganize(String path)
 at System.Linq.Enumerable.SelectManySingleSelectorIterator2.ToArray() at System.Linq.Buffer1..ctor(IEnumerable1 source) at System.Linq.OrderedEnumerable1.GetEnumerator()+MoveNext()
 at System.Linq.Enumerable.WhereEnumerableIterator1.ToList() at Emby.Plugins.JavScraper.JavOrganizeTask.Execute(CancellationToken cancellationToken, IProgress1 progress)
 at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
