### ISSUE TITLE
JavOrganize 不可用

### ISSUE THREAD

**Issue by 4488dsq** [JavScraper/Emby.Plugins.JavScraper#208]
提示如下：Access to the path '/yuan/#recycle' is denied.
at System.IO.Enumeration.FileSystemEnumerator1.CreateDirectoryHandle(String path, Boolean ignoreNotFound) at System.IO.Enumeration.FileSystemEnumerator1.DequeueNextDirectory()
at System.IO.Enumeration.FileSystemEnumerator1.DirectoryFinished() at System.IO.Enumeration.FileSystemEnumerator1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength)
at System.IO.Enumeration.FileSystemEnumerator1.MoveNext() at System.Linq.Enumerable.SelectEnumerableIterator2.ToList()
at Emby.Plugins.JavScraper.JavOrganizeTask.GetFilesToOrganize(String path)
at System.Linq.Enumerable.SelectManySingleSelectorIterator2.ToArray() at System.Linq.Buffer1..ctor(IEnumerable1 source) at System.Linq.OrderedEnumerable1.GetEnumerator()+MoveNext()
at System.Linq.Enumerable.WhereEnumerableIterator1.ToList() at Emby.Plugins.JavScraper.JavOrganizeTask.Execute(CancellationToken cancellationToken, IProgress1 progress)
at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
应该如何解决#recycle不可访问正常，这是回收站

**Comment by bilbil188** [comment]
![QQ截图20210703140322](https://user-images.githubusercontent.com/86825665/124344833-67d7a680-dc07-11eb-9ad2-c134e60681f1.jpg)
![QQ截图20210703140345](https://user-images.githubusercontent.com/86825665/124344837-758d2c00-dc07-11eb-81fd-86796b91722a.jpg)
![QQ截图20210703140402](https://user-images.githubusercontent.com/86825665/124344843-7faf2a80-dc07-11eb-8bd4-ad1586577a02.jpg)

**Comment by 4488dsq** [comment]
找到解决办法了，但是不懂编程不会搞啊~！
The issue might because of this line:
cake/src/Cake.Core/IO/Directory.cs

Line 54 in 8bc1584

 return _directory.GetDirectories(filter, option) 
Stated in .NET api doc here: this API call will thrown UnauthorizedAccessException if the caller does not have the required permission.

It would be great if we could have a chance to use this API:

public System.IO.DirectoryInfo[] GetDirectories (string searchPattern, System.IO.EnumerationOptions enumerationOptions);
From what the doc says, one could set the property of the System.IO.EnumerationOptions enumerationOptions parameter:

//Gets or sets a value that indicates whether to skip files or directories when access is denied (for example, UnauthorizedAccessException or SecurityException). The default is true.
public bool IgnoreInaccessible { get; set; }


引用出处：https://github.com/cake-build/cake/issues/3056
