### ISSUE TITLE
无法获取图片

### ISSUE THREAD

**Issue by vestw** [JavScraper/Emby.Plugins.JavScraper#250]
如题，已排除网络问题，可以搜刮到信息，但无法显示图片，提示错误请求

**Comment by kyalpha313** [comment]
相同问题

**Comment by Nolovenodie** [comment]
我也是, 我的错误日志:

系统 Windows Server 2019 Datacenter
Emby 版本 4.6.7.0
JavScraper 版本 v1.2021.622.2145

2021-11-30 18:10:35.332 Error App: Error in JavScraper
	*** Error Report ***
	Version: 4.6.7.0
	Command line: C:\Users\Administrator\AppData\Roaming\Emby-Server\system\EmbyServer.dll
	Operating system: Microsoft Windows 10.0.17763
	Framework: .NET Core 3.1.21
	OS/Process: x64/x64
	Runtime: C:/Users/Administrator/AppData/Roaming/Emby-Server/system/System.Private.CoreLib.dll
	Processor count: 12
	Data path: C:\Users\Administrator\AppData\Roaming\Emby-Server\programdata
	Application path: C:\Users\Administrator\AppData\Roaming\Emby-Server\system
	System.UriFormatException: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
	   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
	   at Emby.Plugins.JavScraper.Services.ImageProxyService.GetImageResponse(String url, ImageType type, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.ItemImageProvider.DownloadImage(BaseItem item, LibraryOptions libraryOptions, ImageRefreshOptions refreshOptions, IRemoteImageProvider provider, RefreshResult result, IEnumerable`1 images, Int32 minWidth, ImageType type, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseItem item, LibraryOptions libraryOptions, IRemoteImageProvider provider, ImageRefreshOptions refreshOptions, TypeOptions savedOptions, Int32 backdropLimit, List`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)
	Source: System.Private.Uri
	TargetSite: Void CreateThis(System.String, Boolean, System.UriKind)
	
2021-11-30 18:10:35.334 Debug App: Saving nfo metadata for M:\Emby\Porn\JavDB\2.0\HHKL-040\HHKL-040.mp4 to M:\Emby\Porn\JavDB\2.0\HHKL-040\HHKL-040.nfo.

**Comment by bot223** [comment]
好像是标题惹的祸··我把标题格式改为只要番号就正常了

**Comment by imsoulnice** [comment]
和楼主一样的问题

**Comment by RenMu-V** [comment]
和楼主一样的问题

**Comment by RenMu-V** [comment]
已排除网络问题，可以搜刮到信息，但无法显示图片，提示错误请求
