### ISSUE TITLE
emby 4.7.1.0 修复JAVDB抓取数据问题、封面切图可以用了

### ISSUE THREAD

**Issue by bjrjustin** [JavScraper/Emby.Plugins.JavScraper#291]
https://github.com/bjrjustin/Emby.Plugins.JavScraper/releases/tag/v1.2022.0528.1141

**Comment by bjrjustin** [comment]
#262 
感谢这位老兄提醒，原来只需要升级Emby的依赖即可，解决了切图问题

**Comment by bjrjustin** [comment]
日志如下：
2022-05-28 11:46:51.518 Info Emby.Plugins.JavScraper.Scrapers.JavDB: GetHtmlDocumentAsync /search?q=jul-965&f=all
2022-05-28 11:46:52.769 Info Emby.Plugins.JavScraper.JavMovieProvider: GetSearchResults name:jul-965-C id:jul-965 count:1
2022-05-28 11:46:52.808 Info Emby.Plugins.JavScraper.Scrapers.JavDB: GetHtmlDocumentAsync https://javdb001.com/v/xGnmP
2022-05-28 11:46:54.249 Info Emby.Plugins.JavScraper.Scrapers.JavDB: GetHtmlDocumentAsync https://www.dmm.co.jp/mono/dvd/-/detail/=/cid=jul965/
2022-05-28 11:46:56.223 Info Emby.Plugins.JavScraper.Scrapers.JavDB: GetHtmlDocumentByPostAsync https://www.jav321.com/search
2022-05-28 11:46:57.854 Info Emby.Plugins.JavScraper.JavMovieProvider: GetMetadata name:jul-965-C {"OriginalTitle":"【FANZA限定】Madonna電撃移籍第2弾！！ 卒業式の後に…大人になった君へ義母からの贈り物―。 佐田茉莉子 パンティと生写真付き","Plot":"寮に住みながら学園生活を送る誠。充実した3年間はあっという間に終わりを告げ、とうとう卒業式を迎える。実家では憧れの女性・茉莉子が父と再婚したこともあり、気まずさからほとんど帰ることもなかった。だが帰り道、なんと義母となった茉莉子が急遽、卒業祝いに訪れるのだった。その夜、宿泊先で彼女は「大人になった誠君へプレゼント」と優しく口づけを―。憧れの義母に導かれ、彼は大人への階段をまた一つ昇るのだった…。","Director":"ひむろっく","Runtime":"120 分鍾","Studio":"マドンナ(Madonna)","Set":"卒業式の後に…大人になった君へ義母からの贈り物―。","Genres":["婆婆","熟女","已婚婦女","處男","單體作品","戲劇"],"Actors":["佐田茉莉子","結城結弦"],"Samples":["https://c0.jdbstatic.com/samples/xg/xGnmP_l_0.jpg","https://c0.jdbstatic.com/samples/xg/xGnmP_l_1.jpg","https://c0.jdbstatic.com/samples/xg/xGnmP_l_2.jpg","https://c0.jdbstatic.com/samples/xg/xGnmP_l_3.jpg","https://c0.jdbstatic.com/samples/xg/xGnmP_l_4.jpg","https://c0.jdbstatic.com/samples/xg/xGnmP_l_5.jpg","https://c0.jdbstatic.com/samples/xg/xGnmP_l_6.jpg","https://c0.jdbstatic.com/samples/xg/xGnmP_l_7.jpg","https://c0.jdbstatic.com/samples/xg/xGnmP_l_8.jpg","https://c0.jdbstatic.com/samples/xg/xGnmP_l_9.jpg"],"CommunityRating":8.84,"Provider":"JavDB","Url":"https://javdb001.com/v/xGnmP","Num":"JUL-965","Title":"【FANZA限定】Madonna電撃移籍第2弾！！ 卒業式の後に…大人になった君へ義母からの贈り物―。 佐田茉莉子 パンティと生写真付き","Cover":"https://c0.jdbstatic.com/covers/xg/xGnmP.jpg","Date":"2022-05-25"}
2022-05-28 11:47:44.195 Info HttpClient: GET http://192.168.0.100:8096/emby/Plugins/JavScraper/Image?url=https://c0.jdbstatic.com/covers/xg/xGnmP.jpg&type=Primary
2022-05-28 11:47:44.211 Info Emby.Plugins.JavScraper.Services.ImageService: https://c0.jdbstatic.com/covers/xg/xGnmP.jpg
2022-05-28 11:47:44.219 Info App: GetImageResponse-https://c0.jdbstatic.com/covers/xg/xGnmP.jpg
2022-05-28 11:47:45.793 Info App: Save image cache https://c0.jdbstatic.com/covers/xg/xGnmP.jpg /var/lib/emby/cache/images/https%3A%2F%2Fc0.jdbstatic.com%2Fcovers%2Fxg%2FxGnmP.jpg 
2022-05-28 11:47:45.804 Info App: CutImage: staring...
2022-05-28 11:47:46.957 Info App: CutImage: Already cut 800x538 --> start_w: 442

**Comment by windflyer** [comment]
大佬更新的真快！！

**Comment by carlchina** [comment]
FC2 单独识别可以识别出内容，但是确定之后图片不显示，标题变成 NULL NULL
补充一下操作方法：直接用纯数字搜索就会确定后变成NULL NULL，使用 FC2-XXXX 搜索点确定就可以正常显示

**Comment by z3shan33** [comment]
大佬，这个你编译的那个jellyfin支持哪个版本的jellyfin。10.7.7支持吗

**Comment by pdxyyds** [comment]
> https://github.com/bjrjustin/Emby.Plugins.JavScraper/releases/tag/v1.2022.0528.1141

大佬，我发现4.7.0.60放这个新版本，没有设置项了。退回31版本正常

**Comment by UnsignedMe** [comment]
10.8.0 Jellyfin无法使用

**Comment by terrysp** [comment]
不行
GetHtmlDocumentAsync The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

**Comment by wobushiladeng** [comment]
希望大佬继续更新增加更多的功能，更加稳定

**Comment by bjrjustin** [comment]
> FC2 单独识别可以识别出内容，但是确定之后图片不显示，标题变成 NULL NULL 补充一下操作方法：直接用纯数字搜索就会确定后变成NULL NULL，使用 FC2-XXXX 搜索点确定就可以正常显示

FC2 是指FC2-PPV-数字 这种吗？

**Comment by carlchina** [comment]
> 
FC2-PPV-数字 或者 FC2-数字，都是正常的。

**Comment by kingrowing** [comment]
现在是不是抓取不了剧情和简介呢

**Comment by long1215** [comment]
试了下 封面出不来

**Comment by zw900** [comment]
大佬，最新版怎么放到威联通的Jellyfin插件目录，没有反应呀

**Comment by pdxyyds** [comment]
4.7.0.60 无法使用，大佬能更新一下么

**Comment by fcying** [comment]
试了下, 封面出不来, 标题能出来,  emby log里有报错
emby docker 版本  4.7.1.0
```
2022-06-04 12:03:24.236 Error App: System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetAsync(String requestUri, CancellationToken cancellationToken)
   at Emby.Plugins.JavScraper.Http.HttpClientEx.GetAsync(String requestUri, CancellationToken cancellationToken)
   at Emby.Plugins.JavScraper.Services.ImageProxyService.GetImageResponse(String url, ImageType type, CancellationToken cancellationToken)
2022-06-04 12:03:24.236 Error App: Error in JavScraper
        *** Error Report ***
        Version: 4.7.1.0
        Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
        Operating system: Linux version 5.15.35-1-pve (build@proxmox) (gcc (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP PVE 5.15.35-2 (Thu
        Framework: .NET 6.0.2
        OS/Process: x64/x64
        Runtime: system/System.Private.CoreLib.dll
        Processor count: 8
        Data path: /config
        Application path: /system
        System.ArgumentNullException: System.ArgumentNullException: Value cannot be null. (Parameter 'stream')
           at Emby.Providers.Manager.StreamImageSource..ctor(Stream stream, IFileSystem fileSystem, ILogger logger)
           at Emby.Providers.Manager.ProviderManager.SaveImage(BaseItem item, LibraryOptions libraryOptions, Stream source, ReadOnlyMemory`1 mimeType, ImageType type, Nullable`1 imageIndex, Boolean isFallbackImage, CancellationToken cancellationToken)
           at Emby.Providers.Manager.ItemImageProvider.DownloadImage(BaseItem item, LibraryOptions libraryOptions, ImageRefreshOptions refreshOptions, IRemoteImageProvider provider, RefreshResult result, IEnumerable`1 images, Int32 minWidth, ImageType type, CancellationToken cancellationToken)
           at Emby.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseMetadataResult itemResult, LibraryOptions libraryOptions, IRemoteImageProvider provider, ImageRefreshOptions refreshOptions, Boolean replaceAllImages, TypeOptions savedOptions, Int32 backdropLimit, List`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)
        Source: Emby.Providers
        TargetSite: Void .ctor(System.IO.Stream, MediaBrowser.Model.IO.IFileSystem, MediaBrowser.Model.Logging.ILogger)
```

**Comment by wobushiladeng** [comment]
我的也是无法使用

**Comment by fcying** [comment]
在 @bjrjustin  版本的基础上, 加了`base uri`, 在 `emby docker 4.7.20` 上刮削正常了, 别的功能没测试
```
diff --git a/Emby.Plugins.JavScraper/Services/ImageProxyService.cs b/Emby.Plugins.JavScraper/Services/ImageProxyService.cs
index b5ed7cd..0b40ec4 100644
--- a/Emby.Plugins.JavScraper/Services/ImageProxyService.cs
+++ b/Emby.Plugins.JavScraper/Services/ImageProxyService.cs
@@ -80,7 +80,8 @@ namespace Emby.Plugins.JavScraper.Services
             //  /emby/Plugins/JavScraper/Image?url=&type=xx
             if (url.IndexOf("Plugins/JavScraper/Image", StringComparison.OrdinalIgnoreCase) >= 0) //本地的链接
             {
-                var uri = new Uri(url);
+                Uri baseUri = new Uri("https://emby.media/");
+                var uri = new Uri(baseUri, url);
                 var q = HttpUtility.ParseQueryString(uri.Query);
                 var url2 = q["url"];
                 url2 = WebUtility.UrlDecode(url2);
```
[JavScraper.zip](https://github.com/JavScraper/Emby.Plugins.JavScraper/files/8838005/JavScraper.zip)

**Comment by capsshift** [comment]
高手啊，能不能解决一下，女友的头像，现在搞不定啊。

**Comment by iosx** [comment]
封面不显示的，把cache删了，重新刷新元数据试试。

**Comment by Neurotoxin0** [comment]
> https://github.com/bjrjustin/Emby.Plugins.JavScraper/releases/tag/v1.2022.0528.1141

Emby 4.7.1.0 刮削还是有报错
![image](https://user-images.githubusercontent.com/32124086/173208136-229a2381-b112-42c3-a1c2-5fd141b2b1d0.png)

**Comment by maxererer** [comment]
@bjrjustin 大佬，javdb可以抓取，但是
松本菜奈実 JULIA 篠田ゆう 头像与名称都有些错误，不知道是不是引用信息库不对

**Comment by lilijie458** [comment]
> https://github.com/bjrjustin/Emby.Plugins.JavScraper/releases/tag/v1.2022.0528.1141

请问大哥能否支持一下jellyfin？

**Comment by qinxianyuzou** [comment]
大佬这个东西我也不知道是我不会用还是没有配好，完全搜索不到内容，emby4.7.1.0，新入坑小白

**Comment by MccYcore** [comment]
emby最新版本的dll文件没有更新，版本号还是v1.2022.0528.1141

**Comment by bjrjustin** [comment]
> emby最新版本的dll文件没有更新，版本号还是v1.2022.0528.1141

因为是fork的，检查更新的版本还是对应到原仓库的，最新的在https://github.com/bjrjustin/Emby.Plugins.JavScraper/releases/tag/v1.2022.1024.2104

**Comment by danpengapple** [comment]
emby 更新到最新4.7.8刮封面不出来，手到倒是可以，是不是4.7.8不能用，太新版本吗？用的的是最近更新的插件https://github.com/bjrjustin/Emby.Plugins.JavScraper/releases/tag/v1.2022.1024.2104

**Comment by bjrjustin** [comment]
> emby 更新到最新4.7.8刮封面不出来，手到倒是可以，是不是4.7.8不能用，太新版本吗？用的的是最近更新的插件https://github.com/bjrjustin/Emby.Plugins.JavScraper/releases/tag/v1.2022.1024.2104

我也是4.7.8，没有这个问题呢，你可以上传一下你的embyserver.txt日志文件看看呢

**Comment by danpengapple** [comment]
[embyserver.txt](https://github.com/JavScraper/Emby.Plugins.JavScraper/files/9897377/embyserver.txt)
昨晚升级到了4.8测试版也是同样的问题！

**Comment by inforest27** [comment]
辛苦维护的大佬了！
