### ISSUE TITLE
EMBY4.7.2.0表示无法使用

### ISSUE THREAD

**Issue by 15064187978** [JavScraper/Emby.Plugins.JavScraper#299]
EMBY4.7.2.0表示无法使用，请大佬帮忙编译一下最新的4.7.2.0的版本，麻烦了

**Comment by 15064187978** [comment]
不自动采集，封面也不显示

**Comment by 15064187978** [comment]
*** Error Report ***
	Version: 4.7.2.0
	Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /volume1/Emby -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /volume1/Emby/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 4.4.59+ (root@build3) (gcc version 4.9.3 20150311 (prerelease) (crosstool-NG 1.20.0) ) #25426 SMP PREEMPT Mon Dec 14 18:48:50 CST 2020
	Framework: .NET 6.0.2
	OS/Process: x64/x64
	Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 6
	Data path: /volume1/Emby
	Application path: /volume1/@appstore/EmbyServer/system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: Connection to http://subtitle.kankan.xunlei.com:8000/subxl/8C7BCFD77AFECAB2CBE8302911280DA9DD05252B.json timed out
	 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
	 ---> System.TimeoutException: The operation was canceled.
	 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
	 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
	 ---> System.Net.Sockets.SocketException (125): Operation canceled
	   --- End of inner exception stack trace ---
	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
	   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
	   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   --- End of inner exception stack trace ---
	   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
	   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
	   --- End of inner exception stack trace ---
	   --- End of inner exception stack trace ---
	   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
	   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   --- End of inner exception stack trace ---
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at Emby.MeiamSub.Thunder.ThunderProvider.SearchSubtitlesAsync(SubtitleSearchRequest request)
	   at Emby.MeiamSub.Thunder.ThunderProvider.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
	   at Emby.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: Void MoveNext()
	InnerException: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
	Source: System.Net.Http
	TargetSite: Void HandleFailure(System.Exception, Boolean, System.Net.Http.HttpResponseMessage, System.Threading.CancellationTokenSource, System.Threading.CancellationToken, System.Threading.CancellationTokenSource)
	   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
	   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	InnerException: System.TimeoutException: The operation was canceled.
	Source: 
	TargetSite: 
	InnerException: System.Threading.Tasks.TaskCanceledException: The operation was canceled.
	Source: System.Net.Http
	TargetSite: Void MoveNext()
	   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
	   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
	InnerException: System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
	Source: System.Net.Sockets
	TargetSite: Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)
	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
	   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
	   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	InnerException: System.Net.Sockets.SocketException: Operation canceled
	Source: 
	TargetSite: 
	
2022-06-18 09:58:53.229 Info Emby.Plugins.JavScraper.JavMovieProvider: GetMetadata info:{"Name":"SIVR-213 【VR】天音麻痹ASMR特化×喂，喂","MetadataLanguage":"zh-CN","MetadataCountryCode":"CN","ProviderIds":{"JavScraper":"SIVR-213","JavScraper-Json":"{\"OriginalTitle\":\"【VR】天音まひな ASMR特化×おま●こ、くぱぁ\",\"Director\":\"ZAMPA\",\"Runtime\":\"95分鐘\",\"Studio\":\"エスワン ナンバーワンスタイル\",\"Maker\":\"S1 VR\",\"Set\":\"S1 VR\",\"Genres\":[\"VR専用\",\"淫语\",\"巨乳\",\"女上位\",\"单体作品\",\"高品质VR\",\"多選提交\"],\"Actors\":[\"天音まひな\"],\"Samples\":[\"https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-1.jpg\",\"https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-2.jpg\",\"https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-3.jpg\",\"https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-4.jpg\",\"https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-5.jpg\",\"https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-6.jpg\",\"https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-7.jpg\",\"https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-8.jpg\",\"https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-9.jpg\",\"https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-10.jpg\",\"https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-11.jpg\",\"https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-12.jpg\"],\"Provider\":\"JavBus\",\"Url\":\"https://www.javbus.com/SIVR-213\",\"Num\":\"SIVR-213\",\"Title\":\"【VR】天音麻痹ASMR特化×喂，喂\",\"Cover\":\"https://www.javbus.com/pics/cover/900v_b.jpg\",\"Date\":\"2022-06-12\"}","JavScraper-Url":"https://www.javbus.com/SIVR-213"},"Year":2022,"PremiereDate":"2022-06-11T16:00:00.0000000Z","IsAutomated":false,"EnableAdultMetadata":false}
2022-06-18 09:58:56.380 Error Emby.Plugins.JavScraper.Scrapers.JavBus: Response status code does not indicate success: 404 (Not Found).
2022-06-18 09:58:56.381 Info Emby.Plugins.JavScraper.JavMovieProvider: GetMetadata name:SIVR-213 【VR】天音麻痹ASMR特化×喂，喂 {"OriginalTitle":"【VR】天音まひな ASMR特化×おま●こ、くぱぁ","Director":"ZAMPA","Runtime":"95分鐘","Studio":"エスワン ナンバーワンスタイル","Maker":"S1 VR","Set":"S1 VR","Genres":["VR専用","淫語","巨乳","女上位","DMM獨家","單體作品","ハイクオリティVR","多選提交","天音まひな"],"Actors":["天音まひな"],"Samples":["https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-1.jpg","https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-2.jpg","https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-3.jpg","https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-4.jpg","https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-5.jpg","https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-6.jpg","https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-7.jpg","https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-8.jpg","https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-9.jpg","https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-10.jpg","https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-11.jpg","https://pics.dmm.co.jp/digital/video/sivr00213/sivr00213jp-12.jpg"],"Provider":"JavBus","Url":"https://www.javbus.com/SIVR-213","Num":"SIVR-213","Title":"【VR】天音まひな ASMR特化×おま●こ、くぱぁ","Cover":"https://www.javbus.com/pics/cover/900v_b.jpg","Date":"2022-06-12"}
2022-06-18 09:58:56.424 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /var/packages/EmbyServer/target/bin/ffprobe -i file:"/volume1/Media/有码=M=/SDK-046/SDK-046-trailer.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2022-06-18 09:58:56.431 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 1 - Failed
2022-06-18 09:58:56.432 Error App: Error in ffprobe
	*** Error Report ***
	Version: 4.7.2.0
	Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /volume1/Emby -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /volume1/Emby/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 4.4.59+ (root@build3) (gcc version 4.9.3 20150311 (prerelease) (crosstool-NG 1.20.0) ) #25426 SMP PREEMPT Mon Dec 14 18:48:50 CST 2020
	Framework: .NET 6.0.2
	OS/Process: x64/x64
	Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 6
	Data path: /volume1/Emby
	Application path: /volume1/@appstore/EmbyServer/system
	System.Exception: System.Exception: ffprobe failed for file:"/volume1/Media/有码=M=/SDK-046/SDK-046-trailer.mp4" - streams and format are both null: 
	{
	
	}
	
	
	ffprobe version 5.0.0-emby_2022_05_07 Copyright (c) 2007-2022 the FFmpeg developers and softworkz for Emby LLC
	  built with gcc 8.3.0 (crosstool-NG 1.24.0)
	[mov,mp4,m4a,3gp,3g2,mj2 @ 0x105a880] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
	[mov,mp4,m4a,3gp,3g2,mj2 @ 0x105a880] moov atom not found
	file:/volume1/Media/有码=M=/SDK-046/SDK-046-trailer.mp4: Invalid data found when processing input
	
	
	   at Emby.Server.MediaEncoding.Probing.MediaProbeManager.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, String userAgent, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Boolean forceEnableLogging, CancellationToken cancellationToken)
	   at Emby.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](MetadataResult`1 metadataResult, MetadataRefreshOptions options, LibraryOptions libraryOptions, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, MetadataResult`1 itemResult, String logName, MetadataRefreshOptions options, LibraryOptions libraryOptions, RefreshResult refreshResult, CancellationToken cancellationToken)
	Source: Emby.Server.MediaEncoding
	TargetSite: Void MoveNext()
	
2022-06-18 09:58:56.436 Info HttpClient: GET https://api.themoviedb.org/3/configuration?api_key=x_secret1_x
2022-06-18 09:58:57.138 Info App: MovieDb settings: {"images":{"base_url":"http://image.tmdb.org/t/p/","secure_base_url":"https://image.tmdb.org/t/p/","backdrop_sizes":["w300","w780","w1280","original"],"logo_sizes":["w45","w92","w154","w185","w300","w500","original"],"poster_sizes":["w92","w154","w185","w342","w500","w780","original"],"profile_sizes":["w45","w185","h632","original"],"still_sizes":["w92","w185","w300","original"]},"change_keys":["adult","air_date","also_known_as","alternative_titles","biography","birthday","budget","cast","certifications","character_names","created_by","crew","deathday","episode","episode_number","episode_run_time","freebase_id","freebase_mid","general","genres","guest_stars","homepage","images","imdb_id","languages","name","network","origin_country","original_name","original_title","overview","parts","place_of_birth","plot_keywords","production_code","production_companies","production_countries","releases","revenue","runtime","season","season_number","season_regular","spoken_languages","status","tagline","title","translations","tvdb_id","tvrage_id","type","video","videos"]}
2022-06-18 09:58:57.145 Error App: Error in Screen Grabber
	*** Error Report ***
	Version: 4.7.2.0
	Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /volume1/Emby -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /volume1/Emby/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 4.4.59+ (root@build3) (gcc version 4.9.3 20150311 (prerelease) (crosstool-NG 1.20.0) ) #25426 SMP PREEMPT Mon Dec 14 18:48:50 CST 2020
	Framework: .NET 6.0.2
	OS/Process: x64/x64
	Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 6
	Data path: /volume1/Emby
	Application path: /volume1/@appstore/EmbyServer/system
	System.ArgumentNullException: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
	   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
	   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
	   at Emby.Providers.MediaInfo.VideoImageProvider.GetImage(BaseMetadataResult itemResult, ImageType type, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseMetadataResult itemResult, IDynamicImageProvider provider, Boolean providerReportsChanges, ImageRefreshOptions refreshOptions, Boolean replaceAllImages, TypeOptions savedOptions, LibraryOptions libraryOptions, List`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)
	Source: System.Linq
	TargetSite: Void ThrowArgumentNullException(System.Linq.ExceptionArgument)
	
2022-06-18 09:58:57.147 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /var/packages/EmbyServer/target/bin/ffprobe -i file:"/volume1/Media/有码=M=/SDK-046/SDK-046.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2022-06-18 09:58:57.153 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 1 - Failed
2022-06-18 09:58:57.154 Error App: Error in ffprobe
	*** Error Report ***
	Version: 4.7.2.0
	Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /volume1/Emby -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /volume1/Emby/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 4.4.59+ (root@build3) (gcc version 4.9.3 20150311 (prerelease) (crosstool-NG 1.20.0) ) #25426 SMP PREEMPT Mon Dec 14 18:48:50 CST 2020
	Framework: .NET 6.0.2
	OS/Process: x64/x64
	Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 6
	Data path: /volume1/Emby
	Application path: /volume1/@appstore/EmbyServer/system
	System.Exception: System.Exception: ffprobe failed for file:"/volume1/Media/有码=M=/SDK-046/SDK-046.mp4" - streams and format are both null: 
	{
	
	}
	
	
	ffprobe version 5.0.0-emby_2022_05_07 Copyright (c) 2007-2022 the FFmpeg developers and softworkz for Emby LLC
	  built with gcc 8.3.0 (crosstool-NG 1.24.0)
	file:/volume1/Media/有码=M=/SDK-046/SDK-046.mp4: No such file or directory
	
	
	   at Emby.Server.MediaEncoding.Probing.MediaProbeManager.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, String userAgent, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Boolean forceEnableLogging, CancellationToken cancellationToken)
	   at Emby.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](MetadataResult`1 metadataResult, MetadataRefreshOptions options, LibraryOptions libraryOptions, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, MetadataResult`1 itemResult, String logName, MetadataRefreshOptions options, LibraryOptions libraryOptions, RefreshResult refreshResult, CancellationToken cancellationToken)
	Source: Emby.Server.MediaEncoding
	TargetSite: Void MoveNext()
	
2022-06-18 09:58:57.154 Info Emby.Plugins.JavScraper.JavMovieProvider: GetMetadata info:{"Name":"SDK-046-[个人拍摄x 3P] Tsurupeta Geki Kawa Girls和过夜温泉paco之旅","MetadataLanguage":"zh-CN","MetadataCountryCode":"CN","ProviderIds":{},"Year":2022,"PremiereDate":"2022-06-14T16:00:00.0000000Z","IsAutomated":false,"EnableAdultMetadata":false}
2022-06-18 09:58:57.154 Info Emby.Plugins.JavScraper.JavMovieProvider: GetSearchResults id:SDK-046 info:{"Name":"SDK-046-[个人拍摄x 3P] Tsurupeta Geki Kawa Girls和过夜温泉paco之旅","MetadataLanguage":"zh-CN","MetadataCountryCode":"CN","ProviderIds":{},"Year":2022,"PremiereDate":"2022-06-14T16:00:00.0000000Z","IsAutomated":false,"EnableAdultMetadata":false}
2022-06-18 09:58:58.111 Error Emby.Plugins.JavScraper.Scrapers.JavBus: Response status code does not indicate success: 404 (Not Found).
2022-06-18 09:58:59.075 Error Emby.Plugins.JavScraper.Scrapers.JavBus: Response status code does not indicate success: 404 (Not Found).
2022-06-18 09:59:00.020 Error Emby.Plugins.JavScraper.Scrapers.JavBus: Response status code does not indicate success: 404 (Not Found).
2022-06-18 09:59:00.970 Error Emby.Plugins.JavScraper.Scrapers.JavBus: Response status code does not indicate success: 404 (Not Found).
2022-06-18 09:59:02.009 Error Emby.Plugins.JavScraper.Scrapers.JavBus: Response status code does not indicate success: 404 (Not Found).
2022-06-18 09:59:02.157 Error Emby.Plugins.JavScraper.Scrapers.Jav123: The SSL connection could not be established, see inner exception.
2022-06-18 09:59:03.027 Error Emby.Plugins.JavScraper.Scrapers.JavBus: Response status code does not indicate success: 404 (Not Found).
2022-06-18 09:59:07.160 Error Emby.Plugins.JavScraper.Scrapers.Jav123: The SSL connection could not be established, see inner exception.
2022-06-18 09:59:20.991 Error Emby.Plugins.JavScraper.Scrapers.Jav123: Response status code does not indicate success: 404 (Not Found).
2022-06-18 09:59:20.993 Info Emby.Plugins.JavScraper.JavMovieProvider: GetSearchResults name:SDK-046-[个人拍摄x 3P] Tsurupeta Geki Kawa Girls和过夜温泉paco之旅 id:SDK-046 count:1
2022-06-18 09:59:25.996 Error Emby.Plugins.JavScraper.Scrapers.Jav123: The SSL connection could not be established, see inner exception.
2022-06-18 09:59:25.997 Info Emby.Plugins.JavScraper.JavMovieProvider: GetMetadata name:SDK-046-[个人拍摄x 3P] Tsurupeta Geki Kawa Girls和过夜温泉paco之旅 not found 2.
2022-06-18 09:59:26.008 Info Emby.Plugins.JavScraper.JavImageProvider: GetImages name:SDK-046-[个人拍摄x 3P] Tsurupeta Geki Kawa Girls和过夜温泉paco之旅 JavVideoIndex not found.
2022-06-18 09:59:26.011 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /var/packages/EmbyServer/target/bin/ffprobe -i file:"/volume1/Media/有码=M=/pppe-037-C/pppe-037-C.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2022-06-18 09:59:26.075 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded

**Comment by stonejihub** [comment]
试过这个branch吗？ https://github.com/bjrjustin/Emby.Plugins.JavScraper

**Comment by 15064187978** [comment]
[v1.2022.0528.1141](https://github.com/bjrjustin/Emby.Plugins.JavScraper/releases/tag/v1.2022.0528.1141)

您说的是这个版本吗？  这个版本用着呢，也是刮削不全呢
