### ISSUE TITLE
emby配置好後不能刮削

### ISSUE THREAD

**Issue by miraclesuki** [JavScraper/Emby.Plugins.JavScraper#319]
開始刮削直接報錯，貌似是缺了某個Method
![capture](https://user-images.githubusercontent.com/5608626/196376862-95a934db-39fe-4af3-951a-1758a2b2eacc.png)

2022-10-18 15:56:19.430 Error App: Error in JavScraper
        *** Error Report ***
        Version: 4.7.8.0
        Command line: /share/CACHEDEV1_DATA/.qpkg/EmbyServer/system/EmbyServer.dll -programdata /share/CACHEDEV1_DATA/.qpkg/EmbyServer/programdata -ffdetect /share/CACHEDEV1_DATA/.qpkg/EmbyServer/bin/ffdetect -ffmpeg /share/CACHEDEV1_DATA/.qpkg/EmbyServer/bin/ffmpeg -ffprobe /share/CACHEDEV1_DATA/.qpkg/EmbyServer/bin/ffprobe -defaultdirectory /share/CACHEDEV1_DATA/Public -updatepackage emby-server-qnap_{version}_x86_64.qpkg -noautorunwebapp
        Operating system: Linux version 5.10.60-qnap (root@U16BuildServer117) (x86_64-QNAP-linux-gnu-gcc (toolchain config: [gcc-4.9.2 binutils-2.25 glibc-2.21]) 4.9.2, GNU ld
        Framework: .NET 6.0.8
        OS/Process: x64/x64
        Runtime: share/CACHEDEV1_DATA/.qpkg/EmbyServer/system/System.Private.CoreLib.dll
        Processor count: 4
        Data path: /share/CACHEDEV1_DATA/.qpkg/EmbyServer/programdata
        Application path: /share/CACHEDEV1_DATA/.qpkg/EmbyServer/system
        System.MissingMethodException: System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.BaseItem.set_ForcedSortName(System.String)'.
           at Emby.Plugins.JavScraper.JavMovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at Emby.Plugins.JavScraper.JavMovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
           at Emby.Providers.Manager.MetadataService`2.GetMetadataFromProvider(IRemoteMetadataProvider`2 provider, TIdType id, MetadataRefreshOptions options, CancellationToken cancellationToken)
           at Emby.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, LibraryOptions libraryOptions, String logName, TIdType id, IEnumerable`1 providers, MetadataRefreshOptions options, CancellationToken cancellationToken)
        Source: JavScraper
        TargetSite: Void MoveNext()

2022-10-18 15:56:19.430 Info Emby.Plugins.JavScraper.JavImageProvider: GetImages name:RCT268 JavVideoIndex not found.
2022-10-18 15:56:19.441 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /share/CACHEDEV1_DATA/.qpkg/EmbyServer/bin/ffprobe -i file:"/share/ERO/movie/(SOD) 08-01-2011/RCT269.avi" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2022-10-18 15:56:19.956 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded

**Comment by magicianShiro** [comment]
遇到了一样的情况, 老哥有解决吗?

**Comment by moulongxiong** [comment]
同问题，网络已经打通，可以但是无法刮削

**Comment by magicianShiro** [comment]
> 同问题，网络已经打通，可以但是无法刮削

试着用另外一个fork库看看 https://github.com/bjrjustin/Emby.Plugins.JavScraper

**Comment by moulongxiong** [comment]
> > 同问题，网络已经打通，可以但是无法刮削
> 
> 试着用另外一个fork库看看 https://github.com/bjrjustin/Emby.Plugins.JavScraper

查看了emby日志，是插件运行错误导致的，降级成EMBY4.6.7可正常使用，需要作者更新插件适配4.7.X

**Comment by smmya** [comment]
> > > 同问题，网络已经打通，可以但是无法刮削
> > 
> > 
> > 试着用另外一个fork库看看 https://github.com/bjrjustin/Emby.Plugins.JavScraper
> 
> 查看了emby日志，是插件运行错误导致的，降级成EMBY4.6.7可正常使用，需要作者更新插件适配4.7.X

4.6.7还是4.7.6

**Comment by woaijorden** [comment]
> > > 同问题，网络已经打通，可以但是无法刮削
> > 
> > 
> > 试着用另外一个fork库看看 https://github.com/bjrjustin/Emby.Plugins.JavScraper
> 
> 查看了emby日志，是插件运行错误导致的，降级成EMBY4.6.7可正常使用，需要作者更新插件适配4.7.X

降级是重新安装一遍emby4.6.7吗？
