### ISSUE TITLE
手动识别能找到封面图片和电影名字，但是却替换不了是什么情况

### ISSUE THREAD

**Issue by HAN915** [JavScraper/Emby.Plugins.JavScraper#326]
有人碰到这样的问题吗

**Comment by yoqu** [comment]
问题+1

**Comment by HAN915** [comment]
@yoqu 重装emby解决，有人说好像是因为缓存文件问题

**Comment by yoqu** [comment]
你的版本是多少，我看了debug日志好像是版本不对。
2022-12-08 20:13:22.321 Error App: Error in JavScraper
	*** Error Report ***
	Version: 4.7.8.0
	Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /var/packages/EmbyServer/var -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /var/packages/EmbyServer/var/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology7_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 4.4.180+ (root@build15) (gcc version 8.5.0 (GCC) ) #42951 SMP Tue Aug 9 00:54:31 CST 2022
	Framework: .NET 6.0.8
	OS/Process: x64/x64
	Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 8
	Data path: /var/packages/EmbyServer/var
	Application path: /volume1/@appstore/EmbyServer/system
	System.MissingMethodException: System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.BaseItem.set_ForcedSortName(System.String)'.
	   at Emby.Plugins.JavScraper.JavMovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
	   at Emby.Plugins.JavScraper.JavMovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.MetadataService`2.GetMetadataFromProvider(IRemoteMetadataProvider`2 provider, TIdType id, MetadataRefreshOptions options, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, LibraryOptions libraryOptions, String logName, TIdType id, IEnumerable`1 providers, MetadataRefreshOptions options, CancellationToken cancellationToken)
	Source: JavScraper
	TargetSite: Void MoveNext()

**Comment by HAN915** [comment]
@yoqu 重装emby你试了吗？我的是4.7.10

**Comment by moulongxiong** [comment]
同问题

**Comment by moulongxiong** [comment]
已解决，降级emby到4.6可用

**Comment by gtise** [comment]
同样的问题。我换了 docker下重新安装也不行，在群辉下面安装也不行。不晓得问题出在哪里，手动搜索都是可以的，但是不能保存。

**Comment by inforest27** [comment]
> @yoqu 重装emby你试了吗？我的是4.7.10

你插件用的那个版本？

**Comment by wangshuai-007** [comment]
这个库更新解决了这个问题,换他的DLL就行了
https://github.com/bjrjustin/Emby.Plugins.JavScraper/tree/master
