### ISSUE TITLE
4.7.11.0 emby 刮削后的图片无法显示

### ISSUE THREAD

**Issue by wohsj110** [JavScraper/Emby.Plugins.JavScraper#341]

**Comment by Rin-aki** [comment]
同问

**Comment by jackzhang89k** [comment]
看看日志里是否有报错 4.7以上的版本emby升级了依赖库 插件源码要改几个地方重新编译

**Comment by 78wee** [comment]
我也遇到该情况了，4.7 版本以上。刮削后图片无法显示，求解决方法

**Comment by wakloij66778** [comment]
> 看看日志里是否有报错 4.7以上的版本emby升级了依赖库 插件源码要改几个地方重新编译

怎么解决哦 老哥？

**Comment by jackzhang89k** [comment]
> > 看看日志里是否有报错 4.7以上的版本emby升级了依赖库 插件源码要改几个地方重新编译
> 
> 怎么解决哦 老哥？

具体改哪段我不记得了，报错信息里会显示一个Method错误，方法的参数里删掉一个就好了。你可以把报错信息截图贴出来，我就能想起来。反正删了之后编译完我的套件上能正常用。

**Comment by hikaru2025** [comment]
> > > 看看日志里是否有报错 4.7以上的版本emby升级了依赖库 插件源码要改几个地方重新编译
> > 
> > 
> > 怎么解决哦 老哥？
> 
> 具体改哪段我不记得了，报错信息里会显示一个Method错误，方法的参数里删掉一个就好了。你可以把报错信息截图贴出来，我就能想起来。反正删了之后编译完我的套件上能正常用。

System.MissingMethodException: System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.BaseItem.set_ForcedSortName(System.String)'.
	   at Emby.Plugins.JavScraper.JavPersonProvider.GetMetadata(PersonLookupInfo info, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
	   at Emby.Plugins.JavScraper.JavPersonProvider.GetMetadata(PersonLookupInfo info, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.MetadataService`2.GetMetadataFromProvider(IRemoteMetadataProvider`2 provider, TIdType id, MetadataRefreshOptions options, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, LibraryOptions libraryOptions, String logName, TIdType id, IEnumerable`1 providers, MetadataRefreshOptions options, CancellationToken cancellationToken)
	Source: JavScraper
	TargetSite: Void MoveNext()

大佬你看看是不是这个异常信息？
