### ISSUE TITLE
4.7.14.0 挂削成功，但是ffmpeg图片转换报错，导致图片显示不出来

### ISSUE THREAD

**Issue by 1049480196** [JavScraper/Emby.Plugins.JavScraper#346]
日志如下
2023-10-16 17:05:22.077 Error Server: Error processing request
	*** Error Report ***
	Version: 4.7.14.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 4.4.302+ (root@build5) (gcc version 12.2.0 (GCC) ) #64570 SMP Thu Jul 20 00:06:38 CST 2023
	Framework: .NET 6.0.20
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 2
	Data path: /config
	Application path: /system
	System.IO.DirectoryNotFoundException: System.IO.DirectoryNotFoundException: Could not find a part of the path '/emby/Plugins/JavScraper/Image?url=https%3a%2f%2fc0.jdbstatic.com%2fcovers%2fep%2fep5wp.jpg&type=Primary'.
	   at Emby.Drawing.Skia.SkiaEncoder.GetSKFileStream(String path)
	   at Emby.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat selectedOutputFormat)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.(Task )
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Drawing.Skia
	TargetSite: SkiaSharp.SKFileStream GetSKFileStream(System.String)
	Path: /emby/Plugins/JavScraper/Image?url=https%3a%2f%2fc0.jdbstatic.com%2fcovers%2fep%2fep5wp.jpg&type=Primary
	
报错Could not find a part of the path '/emby/Plugins/JavScraper/Image?url=https%3a%2f%2fc0.jdbstatic.com%2fcovers%2fep%2fep5wp.jpg&type=Primary'.
但是实际上通过url地址
ip:8096/emby/Plugins/JavScraper/Image?url=https%3a%2f%2fc0.jdbstatic.com%2fcovers%2fep%2fep5wp.jpg&type=Primary
可以看到图片

使用的分支为：https://github.com/bjrjustin/Emby.Plugins.JavScraper

**Comment by wakloij66778** [comment]
求问分支怎么使用啊老哥？我群晖套件版4.7.14.0连插件都安装不上了 不知道咋回事。。。

**Comment by 1049480196** [comment]
我使用的是docker镜像，插件放在config/plugins 文件夹下就行了

**Comment by wakloij66778** [comment]
我这才重新安装的套件版。。。刮削插件全部安装不上了，，麻了。。

**Comment by feelingfrance** [comment]
识别和刮削都不能用了
