### ISSUE TITLE
能搜刮，不能載入封面 (ubuntu + AWS)

### ISSUE THREAD

**Issue by chanh0** [JavScraper/Emby.Plugins.JavScraper#44]
更新到v1.22.178.0811 后不能载入封面了。墙外，己禁用代理 。 求助

路径 - 影片库\演员\番号\番号.mp4

日志信息如下
2020-06-27 05:08:42.052 Info Emby.Plugins.JavScraper.Services.ImageProxyService: Hit image cache http://pics.dmm.co.jp//digital/video/pred00089/pred00089pl.jpg /var/lib/emby/cache/images/http%3A%2F%2Fpics.dmm.co.jp%2F%2Fdigital%2Fvideo%2Fpred00089%2Fpred00089pl.jpg
2020-06-27 05:08:42.055 Info Emby.Plugins.JavScraper.Services.ImageProxyService: CutImage: staring...
2020-06-27 05:08:42.088 Info Emby.Plugins.JavScraper.Services.ImageProxyService: CutImage: Already cut 800x538 --> start_w: 442
2020-06-27 05:08:42.437 Info Emby.Plugins.JavScraper.JavImageProvider: saved image: Primary
2020-06-27 05:08:42.438 Info Emby.Plugins.JavScraper.JavImageProvider: GetImage found.
2020-06-27 05:08:42.442 Error App: Error in JavScraper
	*** Error Report ***
	Version: 4.4.3.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 5.3.0.1028
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	System.Environment.Version: 3.1.2
	Processor count: 1
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	System.IO.IOException: System.IO.IOException: Input/output error
	   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
	   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
	   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
	   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
	   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileStream(String path, FileOpenMode mode, FileAccessMode access, FileShareMode share, FileOpenOptions fileOpenOptions)
	   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileStream(String path, FileOpenMode mode, FileAccessMode access, FileShareMode share, Boolean isAsync)
	   at MediaBrowser.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseItem item, IDynamicImageProvider provider, Boolean providerReportsChanges, ImageRefreshOptions refreshOptions, TypeOptions savedOptions, LibraryOptions libraryOptions, List`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)
	Source: System.Private.CoreLib
	TargetSite: Void ThrowExceptionForIoErrno(ErrorInfo, System.String, Boolean, System.Func`2[Interop+ErrorInfo,Interop+ErrorInfo])

**Comment by JavScraper** [comment]
看样子是文件操作失败了。检查下影片所在文件夹、emby图片文件夹是否有读写权限。
