### ISSUE TITLE
jellyfin下不工作

### ISSUE THREAD

**Issue by KleinerSource** [JavScraper/Emby.Plugins.JavScraper#9]
jellyfin版本 10.5.0
插件版本 v1.22.66.2105
装上之后 设置界面都有 但是 无法获取到资讯 手动输入番号识别 也没有任何反映
直接刷新源数据  控制台显示
[19:53:33] [INF] [28] App: JavScraper-GetMetadata info:{"Name":"NHDTA-792","MetadataLanguage":"ja","MetadataCountryCode":"JP","ProviderIds":{},"IsAutomated":false}
[19:53:33] [ERR] [28] App: Error in JavScraper
System.MissingMethodException: Method not found: 'System.String MediaBrowser.Model.Extensions.StringHelper.Replace(System.String, System.String, System.String, System.StringComparison)'.
   at Emby.Plugins.JavScraper.JavIdRecognizer.Parse(String name)
   at Emby.Plugins.JavScraper.JavMovieProvider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)
   at Emby.Plugins.JavScraper.JavMovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[19:53:33] [INF] [28] App: JavScraper-JavImageProvider-GetImages name:NHDTA-792
[19:53:33] [INF] [28] App: JavScraper-JavImageProvider-GetImages name:NHDTA-792 JavVideoIndex not found.

挂着代理也一样

**Comment by JavScraper** [comment]
应该是 Jellyfin 更新版本的原因，我下载个新版本试试看。

**Comment by JavScraper** [comment]
试试这个版本。Jellyfin 10.5 和 10.4 的接口不同了。

[Jellyfin@v1.22.75.2214.zip](https://github.com/JavScraper/Emby.Plugins.JavScraper/files/4334316/Jellyfin%40v1.22.75.2214.zip)

**Comment by KleinerSource** [comment]
新版可以正常使用了谢谢
